amazon-braket/amazon-braket-algorithm-library

src/braket/_algos/_version.py

fix: Raise version to 1.1.0
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws-samples/amazon-braket-algorithm-library/blob/main/CONTRIBUTING.md) doc
- [ x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws-samples/amazon-braket-algorithm-library/blob/main/CONTRIBUTING.md#commit-your-change)
- [ x ] I have updated any necessary documentation, including [READMEs](https://github.com/aws-samples/amazon-braket-algorithm-librar …

fix: Raise version to 1.1.0

---

src/braket/experimental/algorithms/grovers_search/grovers_search.md
src/braket/experimental/algorithms/quantum_approximate_optimization/quantum_approximate_optimization.md
src/braket/experimental/algorithms/quantum_phase_estimation/quantum_phase_estimation.md

fix: fix qaoa, qpe, grover url links in md files

fix: fix qaoa, qpe, grover url links in md files

---

notebooks/textbook/Quantum_Phase_Estimation_Algorithm.ipynb
notebooks/textbook/Quantum_Walk.ipynb
notebooks/textbook/Simons_Algorithm.ipynb

update: updating for Aspen-M3

---

setup.py

- Updating dependencies are required for the NBI build.
- Will check after release if the NBI build passes. 
- Tim checked the required notebook runs without other versions. 

fix: update dependencies for NBI Build

---

notebooks/textbook/Quantum_Approximate_Optimization_Algorithm.ipynb

fix: spelling of alternating
*Issue #, if available:* None
*Description of changes:* Fix typo
*Testing done:* None

fix: typo in QAOA

---

setup.py

fix: pin autoray

---

.github/workflows/python-package.yml
setup.py

https://github.com/PennyLaneAI/pennylane/issues/3867
Remove Python 3.7 from GH actions (and pin autoray)

feat: deprecate python 3.7

---

CONTRIBUTING.md

*Issue #, if available:* None
*Description of changes:* Clarify expectation for contributions in our CONTRIBUTING.MD file.
*Testing done:* None

Contribution guideline improvements

---

README.md

*Issue #, if available:* N/A
*Description of changes:* Updating README with details on support.
*Testing done:* None

documentation: Add support info to README

---

.github/workflows/python-package.yml
setup.py

deprecation: deprecate python 3.7

deprecation: deprecate python 3.7

---

README.md

fix: Add python workflow badge for builds

---

setup.py

fix: update openfermion to version 1.1.0

---

src/braket/_algos/_version.py
test/unit_tests/braket/experimental/algorithms/chsh_inequality/test_chsh_inequality.py

fix: add branch coverage for chsh

---

.gitignore

infra: Add JetBrains files to .gitignore

---

test/unit_tests/braket/experimental/algorithms/quantum_circuit_born_machine/test_qcbm.py

- Fixes randomness in the unit test for the init_params passed to the minimization function. 
tox 

fix: randomness in qcbm test

---

setup.cfg
setup.py
src/braket/experimental/algorithms/quantum_circuit_born_machine/qcbm.py
src/braket/experimental/algorithms/simons/simons.py
tox.ini

docs: add a linter to check proper rst formatting and fix up incorrect docs

---

src/braket/experimental/algorithms/qc_qmc/qc_qmc.py
src/braket/experimental/algorithms/quantum_approximate_optimization/quantum_approximate_optimization.py
src/braket/experimental/algorithms/quantum_circuit_born_machine/qcbm.py

doc: add tags to equations for LaTeX rendering in RST docs
Verified manually running
`open build/documentation/html/_apidoc/braket.experimental.algorithms.quantum_circuit_born_machine.html `
etc for all documentation files

doc: add tags to equations for LaTeX rendering in RST docs

---

.github/workflows/python-package.yml

feat: add python 3.11 support

---

.github/workflows/publish-to-pypi.yml

install setuptools explicitly
made this change in other repos

fix: install setuptools

---

.github/workflows/publish-to-pypi.yml

fix: reorder installs for pypi publishing

---

doc/conf.py
setup.cfg

fix: update isort to use a specific profile

---

test/unit_tests/braket/experimental/algorithms/qc_qmc/test_qc_qmc.py

fix: change qmc test device to pennylane default instead of lightning

---

README.md

*Description of changes:* 
Added two summary tables to README.md. One for Braket algorithms and one for community repos.
(not needed, documentation edit)

add summary table to README.md

---

README.md

Put the code in aws solution (https://aws.amazon.com/solutions/implementations/quantum-computing-exploration-for-drug-discovery/) and contribute to braket algorithm library community section. This is the first use case, the use of quantum circuit in reinforcement learning to solve the problem of retrosynthetic planning

update comunity repos sections: quantum-computing-exploration-for-drug-discovery-on-aws 

---

README.md

update description of the community repos section
tox

update description of community repositories

---

setup.py

Dropping the constraint for numpy version.

infra: remove numpy constraint

---

setup.cfg

fix: add parallel testing for pytest

---

setup.py

Sympy 1.13 produces different results for Simon's algorithm

fix: Pin sympy<1.13

---

setup.py
src/braket/experimental/algorithms/qc_qmc/qc_qmc.py

CI is failing (see https://github.com/amazon-braket/amazon-braket-algorithm-library/pull/159) due to recent PennyLane deprecations.
Update usage of PennyLane in this repo to be compatible with recent releases. Update minimum required PennyLane version to 0.34.0 to be consistent with the Braket-PennyLane plugin.
Tests pass. Tested locally with PennyLane 0.34.0 as well as latest releases.
By submitting this pull request, I confirm that my contribution is made under the …

fix: update PennyLane usage

---

.github/workflows/python-package.yml
.readthedocs.yml
pyproject.toml
setup.py

feat: python version upgrade
